parameters:
- name: versionOption
  type: string
  default: patch
  displayName: 'The semantic version type (major, minor, or patch)'

name: layer-storage-$(Date:yyyyMMdd).$(Rev:rr)

trigger: none
  # branches:
  #   include:
  #   - users/*
  # paths:
  #   include:
  #     - /layers/storage
  #     - /scripts
  #   exclude: 
  #     - /**/*.md
  #     - /.attachments

variables:
  - name: system.debug 
    value: true
  - name: downloadPath
    value: $(Build.ArtifactStagingDirectory)
  - name: layerName
    value: storage
  - template: "../../../kits/jumpstart-dependencies/Pipelines/Variables.dev.yaml"
  - template: "../../../kits/jumpstart-dependencies/Pipelines/Variables.yaml"

pool: msftdev-agents 

steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: "Replace tokens in **/*.tfvars, **/*.tf"
  inputs:
    rootDirectory: "$(System.DefaultWorkingDirectory)/layers/${{ variables.layerName}}/Example"
    targetFiles: "**/*.tfvars, **/*.tf"
    tokenPrefix: "__"
    tokenSuffix: "__"
    
- task: AzureCLI@2
  displayName: Layer Deployment
  inputs:
    azureSubscription: DevOps-Patterns-Base-Infrastructure-SPN
    addSpnToEnvironment: true
    scriptType: bash
    scriptLocation: scriptPath
    scriptPath: "$(System.DefaultWorkingDirectory)/scripts/layerstest.sh"
    arguments: dev ${{ variables.backendResourceGroupName}} ${{ variables.backendStorageAccountName}} ${{ variables.backendContainerName}} ${{ variables.tenantId}} ${{ variables.layerName}}

- template: /layers/Version.yaml
  parameters:
    layerName: ${{ variables.layerName}}
    versionOption: ${{ parameters.versionOption }}
        # this variable will be instantiated from an upstream pipeline named manual-version-layers
            triggerPipelineVersionOption: "$(triggerPipelineVersionOption)"
